FROM mirror.gcr.io/library/python:3.12-slim

WORKDIR /app
COPY pyproject.toml README.md ./
COPY lecturelog ./lecturelog
COPY server ./server
COPY cli ./cli
COPY bot ./bot
RUN pip install --no-cache-dir .
COPY . .

CMD ["python", "-m", "bot.main"]
